
[packages.Cython]
version = "0.29.26"

[packages.debugpy]
version = "1.5.1"

[packages.numpy]
version = "1.21.5"
build_pip_requirements = ["Cython==0.29.26"]
cross_pip_requirements = ["robotpy-openblas-dev"]
install_requirements = ["robotpy-openblas"]

[packages.numpy.environment]
F90 = "arm-frc2020-linux-gnueabi-gfortran"

[packages.ptvsd]
version = "4.3.2"

[packages.pydevd]
version = "2.7.0"

[packages.pyinstrument_cext]
version = "0.2.4"

[packages.roslibpy]
version = "1.2.1"

# TODO
# [packages.scipy]
# version = "1.5.3"
